apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: kafka-demo
spec:
  type: NodePort
  selector:
    app: consumer-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
