apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-service
  namespace: kafka-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-service
  template:
    metadata:
      labels:
        app: producer-service
    spec:
      containers:
      - name: producer
        image: producer-service:latest
        imagePullPolicy: IfNotPresent # usar imagem local
        ports:
          - containerPort: 8080
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: kafka-0.kafka:9092,kafka-1.kafka:9092,kafka-2.kafka:9092
