apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
  namespace: kafka-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-service
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
        - name: consumer-service
          image: consumer-service:latest   # precisa dar push no registry
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: kafka-demo
spec:
  selector:
    app: consumer-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer
